Udemy - https://www.udemy.com/course/ai-engineering-complete-bootcamp-masterclass/?couponCode=KEEPLEARNING

Ref Videos - Section 2

In [ ]:
from google.colab import auth
auth.authenticate_user()

# Clone your GitHub repository
!git clone https://github.com/shyamdk/ai_mastery.git
%cd ai_mastery

!git config --global user.email "shyamdk@gmail.com"
!git config --global user.name "Shyam Krishnamurthy"




Cloning into 'ai_mastery'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.
/content/ai_mastery
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address


## Table of Contents
1. [Array Creation](#array-creation)
2. [Working on Arrays](#working=on-arrays)
3. [Basic-opertations](basic-opertations)

In [ ]:
import numpy as np

## Array creation
<a id="array-creation"></a>

In [ ]:



#array from list
a = np.array([1,2,3])
print(a)


#array of zeros
b = np.zeros((2,3))
print(b)


#array of ones
c = np.ones((2,3))
print(c)

#array of range
d = np.arange(10,25,5)
print(d)

#array of evenly spaced values
e = np.linspace(0,2,9)
print(e)


[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


## Working on arrays
<a id="working=on-arrays"></a>

In [ ]:
#working on arrays

#reshape
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2, 3 )
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
#adding dimension
arr = np.array([1,2,3,4,5,6])
reshaped_r = arr[np.newaxis, :]
reshaped_c = arr[:, np.newaxis]
print(reshaped_r)
print(reshaped_c)

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## Basic operations
<a id="basic-opertations"></a>

In [ ]:
#operations on arrays
a = np.arange (1, 6)#a = np.array([1,2,3,4]) #
b = np.arange( 6, 11)#b = np.array([1,2,1,3]) #
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

#mathematical operations
arr = np.array([21, 34, 56])
print(np.sqrt(arr))
print(np.mean(arr))
print(np.sum(arr))

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[4.58257569 5.83095189 7.48331477]
37.0
111


In [ ]:
#array manupilation
#indexing and slicing

arr = np.array([10, 20, 30, 40, 50, 60])
#indexing
print(arr[-1])
print(arr[1])
#slicing
print(arr[:3]) #first 3
print(arr[3:]) #last three
print(arr[1:4]) #index 1 to 3



60
20
[10 20 30]
[40 50 60]
[20 30 40]


In [ ]:
#create multi dimenstional arrage and perform mathematical operations



In [1]:
#After making changes to your notebook, use the following commands to push updates to GitHub:
!git add .
!git commit -m "Updated notebook"
!git push origin main  # Change 'main' to 'master' if needed

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
